SELECT u.id AS client_id,
u."current_age" AS "user_current_age",
u."retirement_age" AS "user_retirement_age",
u."birth_year" AS "user_birth_year",
u."birth_month" AS "user_birth_month",
u."gender" AS "user_gender",
u."address" AS "user_address",
u."latitude" AS "user_latitude",
u."longitude" AS "user_longitude",
u."per_capita_income" AS "user_per_capita_income",
u."yearly_income" AS "user_yearly_income",
u."total_debt" AS "user_total_debt",
u."credit_score" AS "user_credit_score",
u."num_credit_cards" AS "user_num_credit_cards",
u.eligibility_first_card_open_month,
u.eligibility_cards_opened_before_window,
t."id" AS "transaction_id",
t."date" AS "transaction_date",
t."card_id" AS "card_id",
t."amount" AS "transaction_amount",
t."use_chip" AS "transaction_use_chip",
t."merchant_id" AS "transaction_merchant_id",
t."merchant_city" AS "transaction_merchant_city",
t."merchant_state" AS "transaction_merchant_state",
t."zip" AS "transaction_zip",
t."mcc" AS "transaction_mcc",
t."errors" AS "transaction_errors",
t."amount_cents" AS "transaction_amount_cents",
c."card_brand" AS "card_brand",
c."card_type" AS "card_type",
c."card_number" AS "card_number",
c."expires" AS "card_expires",
c."cvv" AS "card_cvv",
c."has_chip" AS "card_has_chip",
c."num_cards_issued" AS "card_num_cards_issued",
c."credit_limit" AS "card_credit_limit",
c."acct_open_date" AS "card_acct_open_date",
c."year_pin_last_changed" AS "card_year_pin_last_changed",
c."card_on_dark_web" AS "card_on_dark_web",
c."card_open_month" AS "card_open_month",
m.description AS mcc_description,
f.label AS fraud_label,
s."signup_id" AS "signup_id",
s."signup_ts" AS "signup_ts",
s."self_reported_source" AS "signup_self_reported_source",
s."signup_landing_page" AS "signup_landing_page"
FROM src.users u
LEFT JOIN src.transactions t ON t.client_id=u.id
LEFT JOIN src.cards c ON c.id=t.card_id AND c.client_id=u.id
LEFT JOIN src.mcc m ON m.mcc=t.mcc
LEFT JOIN src.fraud f ON f.transaction_id=t.id
LEFT JOIN src.signups s ON s.client_id=u.id AND s.card_id=t.card_id;
