
SELECT client_id,
 MAX(user_current_age) AS reported_age,
 MAX(user_gender) AS gender,
 MAX(CAST(REPLACE(user_yearly_income,'$','') AS REAL)) AS annual_income,
 MAX(CAST(REPLACE(user_total_debt,'$','') AS REAL)) AS total_debt,
 MAX(user_credit_score) AS credit_score,
 MAX(user_num_credit_cards) AS reported_card_count,
 MAX(eligibility_cards_opened_before_window) AS cards_opened_before_window,
 COUNT(transaction_id) AS raw_transaction_count,
 SUM(CASE WHEN transaction_errors IS NOT NULL THEN 1 ELSE 0 END) AS error_count,
 SUM(CASE WHEN transaction_amount_cents < 0 THEN 1 ELSE 0 END) AS negative_amount_count,
 SUM(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN 1 ELSE 0 END) AS positive_error_free_count,
 SUM(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN transaction_amount_cents ELSE 0 END) AS positive_error_free_cents,
 SUM(CASE WHEN transaction_amount_cents < 0 AND transaction_errors IS NULL THEN -transaction_amount_cents ELSE 0 END) AS negative_error_free_magnitude_cents,
 COUNT(DISTINCT CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN SUBSTR(transaction_date,1,7) END) AS positive_error_free_months,
 COUNT(DISTINCT CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN SUBSTR(transaction_date,1,10) END) AS positive_error_free_days,
 COUNT(DISTINCT CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN card_id END) AS cards_used,
 COUNT(DISTINCT CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN transaction_mcc END) AS merchant_categories_used,
 MIN(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN transaction_date END) AS first_positive_in_window,
 MAX(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL THEN transaction_date END) AS last_positive_in_window,
 SUM(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL AND card_type='Credit' THEN transaction_amount_cents ELSE 0 END) AS credit_cents,
 SUM(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL AND card_type='Debit' THEN transaction_amount_cents ELSE 0 END) AS debit_cents,
 SUM(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL AND card_type='Debit (Prepaid)' THEN transaction_amount_cents ELSE 0 END) AS prepaid_cents,
 SUM(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL AND transaction_mcc=4829 THEN transaction_amount_cents ELSE 0 END) AS money_transfer_cents,
 SUM(CASE WHEN transaction_id IS NOT NULL AND transaction_amount_cents > 0 AND transaction_errors IS NULL AND transaction_use_chip='Online Transaction' THEN transaction_amount_cents ELSE 0 END) AS online_cents
FROM master GROUP BY client_id
